# Generated by Django 5.2.7 on 2025-10-05 00:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('productions', '0004_alter_budgetline_id_alter_budgetprediction_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('party_name', models.CharField(help_text='Name of the person or company the contract is with.', max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('file', models.FileField(upload_to='finance/contracts/')),
                ('rights', models.JSONField(blank=True, default=dict, help_text="Details about rights, e.g., {'territory': 'Worldwide', 'term': 'Perpetuity'}")),
                ('expiry_alert_sent', models.BooleanField(default=False)),
                ('production', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='productions.production')),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor', models.CharField(max_length=255)),
                ('line_items', models.JSONField(default=list, help_text="List of items, e.g., [{'item': 'Camera Rental', 'cost': 500}]")),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('due_date', models.DateField()),
                ('paid', models.BooleanField(default=False)),
                ('uploaded_invoice', models.FileField(blank=True, null=True, upload_to='finance/invoices/')),
                ('production', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='productions.production')),
            ],
        ),
    ]
