# Generated by Django 5.2.7 on 2025-10-04 05:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Production',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pre', 'Pre-production'), ('shooting', 'Shooting'), ('post', 'Post-production'), ('completed', 'Completed')], max_length=20)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BudgetLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('estimated_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('actual_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('vendor', models.CharField(blank=True, max_length=255)),
                ('approved', models.BooleanField(default=False)),
                ('production', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_lines', to='productions.production')),
            ],
        ),
        migrations.CreateModel(
            name='Scene',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('pages', models.DecimalField(decimal_places=2, max_digits=4)),
                ('props', models.JSONField(blank=True, default=dict)),
                ('characters', models.JSONField(blank=True, default=list)),
                ('estimated_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('production', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scenes', to='productions.production')),
            ],
        ),
        migrations.CreateModel(
            name='Shot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shot_number', models.PositiveIntegerField()),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('todo', 'To Do'), ('in_progress', 'In Progress'), ('done', 'Done')], default='todo', max_length=20)),
                ('vfx_required', models.BooleanField(default=False)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shots', to=settings.AUTH_USER_MODEL)),
                ('scene', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shots', to='productions.scene')),
            ],
        ),
    ]
