# Generated by Django 5.2.7 on 2025-10-04 15:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScriptBreakdown',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('characters', models.JSONField(default=list)),
                ('props', models.JSONField(default=list)),
                ('locations', models.JSONField(default=list)),
                ('stunts', models.JSONField(default=list)),
                ('special_effects', models.JSONField(default=list)),
                ('raw_text', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('production', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='script_breakdowns', to='productions.production')),
            ],
        ),
    ]
