# Generated by Django 5.2.7 on 2025-10-04 17:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productions', '0002_scriptbreakdown'),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetPrediction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('predicted_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('details', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('production', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_predictions', to='productions.production')),
            ],
        ),
    ]
