# Generated by Django 5.2.7 on 2025-10-05 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productions', '0004_alter_budgetline_id_alter_budgetprediction_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scriptbreakdown',
            old_name='characters',
            new_name='schedule_data',
        ),
        migrations.RemoveField(
            model_name='scriptbreakdown',
            name='locations',
        ),
        migrations.RemoveField(
            model_name='scriptbreakdown',
            name='props',
        ),
        migrations.RemoveField(
            model_name='scriptbreakdown',
            name='special_effects',
        ),
        migrations.RemoveField(
            model_name='scriptbreakdown',
            name='stunts',
        ),
    ]
