# Generated by Django 5.2.7 on 2025-10-04 08:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('productions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='vfx/assets/')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VFXShot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('review', 'In Review'), ('approved', 'Approved'), ('omitted', 'Omitted')], default='pending', max_length=20)),
                ('assigned_team', models.CharField(blank=True, help_text='Name of the team or vendor.', max_length=100)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('production', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vfx_shots', to='productions.production')),
                ('scene', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vfx_shots', to='productions.scene')),
                ('shot', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vfx_shot', to='productions.shot')),
            ],
        ),
        migrations.CreateModel(
            name='ShotVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.PositiveIntegerField()),
                ('file', models.FileField(upload_to='vfx/versions/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('approved', models.BooleanField(default=False)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('vfx_shot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='vfx.vfxshot')),
            ],
            options={
                'ordering': ['-version_number'],
                'unique_together': {('vfx_shot', 'version_number')},
            },
        ),
    ]
