# Generated by Django 5.2.7 on 2025-10-04 06:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('productions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CallSheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('scenes', models.JSONField(default=list, help_text='List of scene numbers to be shot.')),
                ('crew_assignments', models.JSONField(default=dict, help_text='Dict mapping user IDs to their call times and roles for the day.')),
                ('locations', models.JSONField(default=list, help_text='List of locations for the day with addresses and notes.')),
                ('published', models.BooleanField(default=False)),
                ('production', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='call_sheets', to='productions.production')),
            ],
        ),
        migrations.CreateModel(
            name='DailyProductionReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dpr_date', models.DateField()),
                ('scenes_completed_list', models.JSONField(default=list, help_text='List of scenes completed.')),
                ('issues', models.JSONField(default=dict, help_text='Notes on issues encountered during the day.')),
                ('expenses', models.JSONField(default=list, help_text='List of expenses incurred.')),
                ('production', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dprs', to='productions.production')),
            ],
        ),
        migrations.CreateModel(
            name='CrewCheckIn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in_time', models.DateTimeField(auto_now_add=True)),
                ('call_sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='check_ins', to='scheduling.callsheet')),
                ('crew_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='check_ins', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('call_sheet', 'crew_member')},
            },
        ),
    ]
